# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Brackup
version:      0.91
version_from: lib/Brackup.pm
installdirs:  site
requires:
    DBD::SQLite:                   0
    DBI:                           0
    Digest::SHA1:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
